(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "fill-column-indicator")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "auto-complete")
(depends-on "pos-tip")
(depends-on "jedi")
(depends-on "projectile")
(depends-on "flx-ido")
(depends-on "js2-mode")
(depends-on "tern")
(depends-on "tern-auto-complete")
(depends-on "yasnippet")
